realLearning/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('textbook.urls')),
    path('textbook/', include('textbook.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

textbook/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contents/<title>', views.contents, name='contents')
]

textbook/models.py
from django.db import models



class Textbook(models.Model):
    title = models.CharField(max_length=50)
    cover_image = models.ImageField(upload_to='textbooks', blank=True)
  
    def __str__(self):
        return self.title



class Chapter(models.Model):
    textbook = models.ForeignKey(Textbook, on_delete=models.CASCADE)
    number = models.IntegerField()
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=500, blank=True, default="")
    intro = models.TextField(blank=True, default="")

    def __str__(self):

        return self.textbook.title +": "+str(self.number) +" "+ self.title
    

class Section(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    number = models.IntegerField()
    title = models.CharField(max_length=50)
    text = models.TextField(blank=True, default="")

    def __str__(self):
        rep = "%s  %d.%d %s" %  (self.chapter.textbook,self.chapter.number,self.number,self.title)
        return rep
    
   

textbook/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.template import loader

from .models import Textbook

def index(request):
    textbooks = Textbook.objects.all()
    return render(request, 'textbook/index.html', {"textbooks" : textbooks })

def contents(request, title):
    book = Textbook.objects.get(title=title)
    return render(request, 'textbook/contents.html', {"book" : book})



# Create your views here.

textbook/templates/textbook/base.html
<!doctype html>
<html lan="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Real Learning</title>
  </head>
  
  <body>
    <h1>Real Learning</h1>
    <p>Welcome to an open platform for collaborative learning </p>


    {% block 'body' %}

    
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>

</html>

textbook/templates/textbook/book.html
{% extends "textbook/base.html" %}

{% block 'body' %}
<h3>Table of Contents</h3>
<h1>

  {{ book.title }}
  <ul style="list-style-type:circle">
  {% for chapter in book.chapter_set.all %}
  <h3>
    <li>
      {{ chapter.title }}
    </li>
  </h3>
  {% endfor %}
  </ul>
{% endblock %}

textbook/templates/textbook/contents.html
{% extends "textbook/base.html" %}

{% block 'body' %}

<img src="{{ book.cover_image.url }}" alt="Cover Image"/>
<h1>{{ book.title }} </h1>
<h3>Table of Contents</h3>

<ol>
  {% for chapter in book.chapter_set.all %}
    <li>
      {{ chapter.title }}
      {% for section in chapter.section_set.all %}
      <ul>
	<li>
	  {{ chapter.number }}.{{ section.number }} {{ section.title }}
	</li>
      </ul>
      {% endfor %}
    </li>
  {% endfor %}
</ol>


{% for chapter in book.chapter_set.all %}
<h1>Chapter {{ chapter.number }}</h1>
<h2>{{ chapter.title }} </h2>
<div>
  <h4>{{ chapter.subtitle }}</h4>
</div>

<p>
  {{ chapter.intro }}
</p>
{% for section in chapter.section_set.all %}

<div>
  <h5>{{ chapter.number }}.{{ section.number }} {{ section.title }}</h5>
</div>
<p>{{ section.text }} </p>

{% endfor %}}



{% endfor %}



{% endblock %}

textbook/templates/textbook/index.html
{% extends "textbook/base.html" %}

{% block 'body' %}
<table class="table table-bordered">
  <thead>
    <tr>
      {% for textbook in textbooks %}	  
      <th>
	{{ textbook.title }}
      </th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for textbook in textbooks %}
      <td>
	<img style="max-width:200px" src="{{ textbook.cover_image.url }}" alt="Physics textbook cover"/>
      </td>
      {% endfor %}
    <tr>
  </tbody>
</table>
{% endblock %}